"""Atlas-core domain schemas — public API."""

from atlas_core.schemas.agent_contract import (
    ContextEnvelope,
    ContextSource,
    ContractVersion,
    InstructionSource,
    ModelIdentity,
    SessionBootstrap,
    SurfaceIdentity,
    ToolCapability,
    ToolCatalog,
    WorkspaceIdentity,
)
from atlas_core.schemas.brain import BrainEdge, BrainNode
from atlas_core.schemas.control_plane import (
    AtlasConfig,
    AuthStatus,
    CockpitConfig,
    ConfigPatchRequest,
    ContextConfig,
    ControlPlaneError,
    ControlPlaneSnapshot,
    GatewayConfig,
    ModulesConfig,
    PermissionConfig,
    ProviderConfig,
    ProviderModelStatus,
    RuntimeConfig,
    SettingStatus,
)
from atlas_core.schemas.core import (
    SECRET_PATTERNS,
    Artifact,
    AuditEvent,
    Mission,
    Run,
    Source,
    ToolCall,
    WikiPage,
)
from atlas_core.schemas.discord import (
    DiscordAction,
    DiscordApproval,
    DiscordApprovalStatus,
)
from atlas_core.schemas.registry_v2 import (
    ModelV2,
    Provider,
    RoutePolicy,
)
from atlas_core.schemas.surface_session import (
    EventKind,
    SessionState,
    SurfaceEvent,
    SurfaceSession,
)

__all__ = [
    "Artifact",
    "AtlasConfig",
    "AuthStatus",
    "AuditEvent",
    "BrainEdge",
    "BrainNode",
    "ContextEnvelope",
    "ContextSource",
    "ContractVersion",
    "CockpitConfig",
    "ConfigPatchRequest",
    "ContextConfig",
    "ControlPlaneError",
    "ControlPlaneSnapshot",
    "DiscordAction",
    "DiscordApproval",
    "DiscordApprovalStatus",
    "EventKind",
    "GatewayConfig",
    "Mission",
    "ModelV2",
    "ModelIdentity",
    "ModulesConfig",
    "PermissionConfig",
    "Provider",
    "ProviderConfig",
    "ProviderModelStatus",
    "RoutePolicy",
    "Run",
    "RuntimeConfig",
    "SECRET_PATTERNS",
    "SessionBootstrap",
    "SessionState",
    "Source",
    "SurfaceEvent",
    "SurfaceIdentity",
    "SurfaceSession",
    "SettingStatus",
    "ToolCall",
    "ToolCapability",
    "ToolCatalog",
    "WikiPage",
    "WorkspaceIdentity",
    "InstructionSource",
]
